### ISSUE TITLE
Undefined index: hide_presets

### ISSUE THREAD

**Issue by jcohlmeyer** [edalzell/statamic-powertools#14]
After upgrading from `1.5` to `1.6` I get this error: `Undefined index: hide_presets`

I guess it is because I don’t have `hide_presets` in my settings file …

## Possible fix
`@unless (isset($settings['hide_presets']) && $settings['hide_presets'])` at line 37 of `widget.blade.php`

**Comment by edalzell** [comment]
Fixed in 1.6.1
