### ISSUE TITLE
2.10.0 Bug with /cp/addons/power-tools/logs

### ISSUE THREAD

**Issue by Bferreira5** [edalzell/statamic-powertools#15]
Running into a few 2.10.0 breaking changes on a few pages with PoweTools in the CP. You probably already have seen some of these. 

**ErrorException in PowerToolsController.php line 54: Non-static method** 
`Rap2hpou=tre\LaravelLogViewer\LaravelLogViewer::all() should not be called statically`

Attaching stack trace
[log.txt](https://github.com/edalzell/statamic-powertools/files/2206282/log.txt)

Essentially just throwing a error on logs page.

**Comment by dannyuk1982** [comment]
Same as this: https://github.com/aryehraber/statamic-logbook/issues/1

Fixed here: https://github.com/aryehraber/statamic-logbook/pull/2

**Comment by Bferreira5** [comment]
Got it. Will wait for next release. Thanks!

**Comment by edalzell** [comment]
@dannyuk1982 can you PR here and I’ll merge and release?
