### ISSUE TITLE
Get prompted to install Xcode on local setup

### ISSUE THREAD

**Issue by paulburgess** [edalzell/statamic-powertools#21]
Hi - I get a prompt to install Xcode when I activate the add-on, with no way to say 'no thanks'. Is there a way to stop this happening?

Many thanks!

**Comment by edalzell** [comment]
what do you mean "activate"? Can you show me the error?

This is not really a power tools issue, more likely a composer issue with your local environment.

**Comment by edalzell** [comment]
closed due to lack of response
